### PR TITLE
support lcov files without TN

### PR DESCRIPTION
**Pull request by Cheekie25**
Some lcov files don't have a `TN:` field.
The parser currently crashes in this case.
Just set `current_test_name` to empty at the beginning to handle this case.

The documentation
https://manpages.ubuntu.com/manpages/noble/man1/geninfo.1.html  
seems to say that the testname is indeed optional:

```
If available, a tracefile begins with the testname which is stored in the following format:

         TN:<test name>
```

### CODE REVIEW

**Comment by RPGillespie6** [comment]
Thanks for this, do you mind adding a test case for this to `run_all.sh`?

You can just add a `test1.no_tn.info` to https://github.com/RPGillespie6/fastcov/tree/master/test/functional/expected_results

And then add a test case here:
https://github.com/RPGillespie6/fastcov/blob/master/test/functional/run_all.sh#L131

```
# Combine operation - Missing TN
coverage run -a ${TEST_DIR}/fastcov.py -C ${TEST_DIR}/expected_results/test1.no_tn.info --loc -o test1.no_tn.actual.info
cmp test1.no_tn.actual.json ${TEST_DIR}/expected_results/combine5.expected.info
```

If not I can merge and do the test case myself

**Comment by RPGillespie6** [comment]
Looks good, thanks for adding the test.

**Comment by Cheekie25** [comment]
> Looks good, thanks for adding the test.

Thank you.
Would you mind releasing a new version with those two changes ?

**Comment by RPGillespie6** [comment]
Done

**Pull request merged**
