### PR TITLE
Two fixes for issue #77: --process-gcno and/or --zerocounters

### PR DESCRIPTION
**Pull request by johan-boule**
Two fixes for issue #77:
--process-gcno: also process gcda files
--zerocounters: do not delete gcno files

### CODE REVIEW

**Comment by RPGillespie6** [comment]
Changes look good, thanks!

The CI pipeline is failing because the coverage report generated by `--process-gcno` on test cases is different now, so when it compares actual coverage report to expected coverage report, the comparison fails. You don't necessarily have to fix this unless you want to dive into the `test/` folder, but let me just verify coverage correctness when `--process-gcno` is present. If it looks good I'll go ahead and merge even with the failing pipeline, and I'll just update all the expected coverage reports to be the new ones generated.

**Comment by RPGillespie6** [comment]
Ok, it looks like from the test output that we are getting double coverage now. In other words, the line hits and branch hits are double what they should be. I believe what is happening is when fastcov invokes `gcov foo.gcno`, gcov is implicitly processing both `foo.gcno` and `foo.gcda`. So with this new change fastcov is now invoking `gcov foo.gcno foo.gcda` which causes gcov to process the gcda twice, hence the double coverage. 

So it may be that the only bug that needs fixing is the zerocounters one. Let me try to confirm in gcov's source

**Comment by RPGillespie6** [comment]
Yeah, it looks like gcov doesn't actually care about the file extensions of the files passed -- it strips off the extension and searches for .gcno/.gcda. I'm wondering now if `--process-gcno` actually does anything if gcov strips off the extension.

https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/gcc/gcov.c#L1585
```
  /* Remove the extension.  */
  cptr = strrchr (CONST_CAST (char *, lbasename (name)), '.');
  if (cptr)
    *cptr = 0;

  length = strlen (name);

  bbg_file_name = XNEWVEC (char, length + strlen (GCOV_NOTE_SUFFIX) + 1); // GCOV_NOTE_SUFFIX = .gcno
  strcpy (bbg_file_name, name);
  strcpy (bbg_file_name + length, GCOV_NOTE_SUFFIX);

  da_file_name = XNEWVEC (char, length + strlen (GCOV_DATA_SUFFIX) + 1); // GCOV_NOTE_SUFFIX = .gcda
  strcpy (da_file_name, name);
  strcpy (da_file_name + length, GCOV_DATA_SUFFIX);
  ```

(I should be an expert on this by now, but I actually haven't thought about fastcov for a while)

**Comment by RPGillespie6** [comment]
Ah... got it.

As you said earlier, gcno is a superset of gcda. So there may be fewer gcda than gcno. Hence, `--process-gcno` can be used if you want to get (empty) coverage of files that were not touched by tests.

Ok, so `--process-gcno` is working correctly. gcov strips off file extension of whatever files fastcov gives it and searches for `.gcno` and `.gcna` variants of the base filenames. The only bug here is that we should not delete .gcno if both `--process-gcno` and `--zerocounters` are passed. I'm going to close this PR and make that tiny fix and #77 should be fixed.

**Comment by johan-boule** [comment]
Sorry, I didn't catch the regression. I was only looking at the percentage printed by fastcov_summary.

**Comment by RPGillespie6** [comment]
No worries, that's why the automated tests are there! I appreciated the PR you opened too - most people aren't willing to contribute.

**Pull request closed without merging**
